### ISSUE TITLE
Tools in camping inventory lost when exiting the end

### ISSUE THREAD

**Issue by atshartman** [Rikmuld/MC-Camping#55]
When leaving the end through the portal all camping tools including the items in the backpack is lost.

**Comment by Gunner76th** [comment]
@atshartman in order for the mod author to assist you, he needs to know a few things first. 
What version of Minecraft are you running?
What version of Forge are you running?
What version of The Camping Mod are you running?
Can you recreate the issue, and then submit a console log (full unedited) so that the mod author can see what is going on at the moment the issue occurs? Post console logs to http://gist.github.com

**Comment by Rikmuld** [comment]
Sorry for the late response, I was gone for the last 2 weeks (introduction on a university).

@atshartman thank you for reporting a bug, but as @Gunner76th stated, it would be very helpful if you could provide some more info. Nonetheless, I shall do my best to fix it if I can replicate it in the newest version of the mod.
