### ISSUE TITLE
Server Crash - java.lang.NullPointerException: Exception getting block type in world

### ISSUE THREAD

**Issue by ProsperCraft** [Rikmuld/MC-Camping#57]
http://pastebin.com/JMf3f8Mq

**Comment by Gunner76th** [comment]
@ProsperCraft are you able to recreate this crash without running cauldron? If you are not able to recreate this crash while not running cauldron, I am not sure if there is anything the mod author can or will do. Most mod authors do not accept or even deal with crashes stemming from the use as Cauldron, because of the nature in which is messes with the backend code in order to allow both bukkit and forge mods to be ran on the same server. 

Also, what were you doing when this crash occurred? was this during server startup, while just walking around, interacting with a block? Posting a crash report is a good start, but providing the information on what you were doing when the crash happened is also needed.

**Comment by Alaberti** [comment]
I have just gotten this crash on a dedicated server. http://pastebin.com/4AniuNA1. 

This is running Forge 1517 on Minecraft 1.7.10 using version 2.1g of the Camping Mod. I was not around when the crash happened, unfortunately, so I can only provide what is in this crash log. Thank you.

**Comment by Gunner76th** [comment]
Just an update for anyone viewing this thread, as per a reply from the mod author with whom I have spoken with, there will be no further updates past 2.1g for the 1.7.10 version of this mod. The author is currently busy with the 1.8 version in which all of the issues have either been resolved, or will be shortly. 

Please see the author's reply here regarding updates and 1.7.10 https://github.com/Rikmuld/CampingMod-mcmod/issues/58

**Comment by Gunner76th** [comment]
@Rikmuld Because this is a 1.7.10 bug report, and there will be no further updates to 1.7.10, can this thread be closed?
